export const navList = [
  {
    title: "Početna",
    link: "/",
  },
  {
    title: "Proizvodi",
    list: [
      {
        title: "Separei",
        link: "/separei",
      },
      {
        title: "Stolice",
        link: "/stolice",
      },
      {
        title: "Stolovi",
        link: "/stolovi",
      },
      {
        title: "Enterijeri",
        link: "/enterijeri",
      },
      {
        title: "Apartmani",
        link: "/apartmani",
      },
    ],
  },
  {
    title: "Kontakt",
    link: "kontakt",
  },
];

export interface Restorani {
  title: string;
  img: string;
}

export const restorani = [
  {
    title: "Zvezdara Teatar",
    img: "/logo-resto-150x150.png",
  },
  {
    title: "Ritual -West 75",
    img: "/logotip-white.webp",
  },
  {
    title: "Kod deda Stavre NBG",
    img: "/Logo-Deda-Stavra-pecenjara-e1711384164435.webp",
  },
  {
    title: "Block-Nbg",
    img: "/Screenshot_20250131_101411_Instagram.jpg",
  },
  {
    title: "DOK 61-Nbg",
    img: "/Screenshot_20250131_102603_Instagram.jpg",
  },
  {
    title: "SteCo Fabrika-Beograd",
    img: "/Screenshot_20250131_101145_Instagram.jpg",
  },
  {
    title: "Great-Cirih",
    img: "/Screenshot_20250131_103458_Gallery.jpg",
  },
];

export interface Diskoteke {
  title: string;
  img: string;
}

export const diskoteke = [
  {
    title: "Eschelon",
    img: "/Screenshot_20250131_112918_Instagram.jpg",
  },
  {
    title: "Trezor",
    img: "/Screenshot_20250131_114623_Instagram.jpg",
  },
  {
    title: "Wave-Kladovo",
    img: "/Screenshot_20250131_120145_Instagram.jpg",
  },
  {
    title: "Sound Factory - Augsburg",
    img: "/SF-Logo-B-Light-1024x665-1.webp",
  },
  {
    title: "Viscose-Luzern",
    img: "/Viscose_Logo-300px.png",
  },
  {
    title: "Hedonic-Cirih",
    img: "/Screenshot_20250131_122015_Facebook.jpg",
  },
  {
    title: "Cuba libre",
    img: "/Screenshot_20250131_113046_Instagram.jpg",
  },
];

export interface CaffeBar {
  title: string;
  img: string;
}

export const caffeBar = [
  {
    title: "Swiss De Light",
    img: "/Swiss-Delight-Linear-White-Logo.png",
  },
  {
    title: "Pauza",
    img: "/Screenshot_20250201_014036_Instagram.jpg",
  },
  {
    title: "Troy",
    img: "/306000680_483699337098345_3057657617767782222_n.jpg",
  },
  {
    title: "Toro",
    img: "/Toro-Logo_Cocoa_Strapline.png",
  },
  {
    title: "Shisha bar Shisharka, Zlatibor",
    img: "/424988200_762183779163092_7151935030057208089_n.jpg",
  },
  {
    title: "Shisha bar Knez Mihajlova",
    img: "/277792341_386705210127294_6218620048571516536_n.jpg",
  },
  {
    title: "Pizzeria PIGO",
    img: "/Screenshot_20250201_015425_Instagram.jpg",
  },
  {
    title: "Pivnica Kompas",
    img: "/400x400-logo-6A2.gif",
  },
  {
    title: "Beer Hub",
    img: "/326401097_1400914950442555_8125295370593203813_n.jpg",
  },
  {
    title: "IKL Wine bar",
    img: "/Screenshot_20250201_015921_Instagram.jpg",
  },
];

export interface Igraonice {
  title: string;
  img: string;
}

export const igraonice = [
  {
    title: "Magicna šuma",
    img: "/Screenshot_20250131_130406_Instagram.jpg",
  },
  {
    title: "Fenix",
    img: "/Screenshot_20250131_130956_Instagram.jpg",
  },
  {
    title: "Poco loco",
    img: "/l_35b60d12d166486f68f53c6258f8777d_1736_rodjendanko_v.jpg",
  },
  {
    title: "Make a wish",
    img: "/Screenshot_20250131_131212_Instagram.jpg",
  },
];

export const separei: string[] = [
  "/separei/separe (3).jpg",
  "/separei/separe (4).jpg",
  "/separei/separe (5).jpg",
  "/separei/separe (2).jpg",
  "/separei/separe (6).jpg",
  "/separei/separe (7).jpg",
  "/separei/separe (8).jpg",
  "/separei/separe (9).jpg",
  "/separei/separe (10).jpg",
  "/separei/separe.jpg",
  "/separei/separe (11).jpg",
  "/separei/separe (12).jpg",
  "/separei/separe (13).jpg",
  "/separei/separe (14).jpg",
  "/separei/separe (15).jpg",
  "/separei/separe (16).jpg",
  "/separei/separe (17).jpg",
  "/separei/separe (18).jpg",
  "/separei/separe (19).jpg",
  "/separei/separe (20).jpg",
  "/separei/separe (21).jpg",
  "/separei/separe (22).jpg",
  "/separei/separe (23).jpg",
  "/separei/separe (24).jpg",
  "/separei/separe (25).jpg",
  "/separei/separe (26).jpg",
  "/separei/separe (27).jpg",
  "/separei/separe (28).jpg",
  "/separei/separe (29).jpg",
  "/separei/separe (30).jpg",
  "/separei/separe (31).jpg",
  "/separei/separe (32).jpg",
  "/separei/separe (33).jpg",
  "/separei/separe (34).jpg",
  "/separei/separe (35).jpg",
  "/separei/separe (36).jpg",
  "/separei/separe (37).jpg",
  "/separei/separe (38).jpg",
  "/separei/separe (39).jpg",
  "/separei/separe (40).jpg",
  "/separei/separe (41).jpg",
  "/separei/separe (42).jpg",
  "/separei/separe (43).jpg",
  "/separei/separe (44).jpg",
  "/separei/separe (45).jpg",
  "/separei/separe (46).jpg",
  "/separei/separe (47).jpg",
  "/separei/separe (48).jpg",
  "/separei/separe (49).jpg",
  "/separei/separe (50).jpg",
  "/separei/separe (51).jpg",
  "/separei/separe (52).jpg",
  "/separei/separe (53).jpg",
  "/separei/separe (54).jpg",
  "/separei/separe (55).jpg",
  "/separei/separe (56).jpg",
  "/separei/separe (57).jpg",
  "/separei/separe (58).jpg",
  "/separei/separe (59).jpg",
  "/separei/separe (60).jpg",
  "/separei/separe (61).jpg",
  "/separei/separe (62).jpg",
  "/separei/separe (63).jpg",
  "/separei/separe (64).jpg",
  "/separei/separe (65).jpg",
  "/separei/separe (66).jpg",
  "/separei/separe (67).jpg",
  "/separei/separe (68).jpg",
  "/separei/separe (69).jpg",
  "/separei/separe (70).jpg",
  "/separei/separe (71).jpg",
  "/separei/separe (72).jpg",
  "/separei/separe (73).jpg",
  "/separei/separe (74).jpg",
  "/separei/separe (75).jpg",
  "/separei/separe (76).jpg",
  "/separei/separe (77).jpg",
  "/separei/separe (78).jpg",
  "/separei/separe (79).jpg",
  "/separei/separe (80).jpg",
  "/separei/separe (81).jpg",
  "/separei/separe (82).jpg",
  "/separei/separe (83).jpg",
  "/separei/separe (84).jpg",
  "/separei/separe (85).jpg",
  "/separei/separe (86).jpg",
  "/separei/separe (87).jpg",
  "/separei/separe (88).jpg",
  "/separei/separe (89).jpg",
  "/separei/separe (90).jpg",
  "/separei/separe (91).jpg",
  "/separei/separe (92).jpg",
  "/separei/separe (93).jpg",
  "/separei/separe (94).jpg",
  "/separei/separe (95).jpg",
  "/separei/separe (96).jpg",
  "/separei/separe (97).jpg",
  "/separei/separe (98).jpg",
  "/separei/separe (99).jpg",
  "/separei/separe (100).jpg",
  "/separei/separe (101).jpg",
  "/separei/separe (102).jpg",
  "/separei/separe (103).jpg",
  "/separei/separe (104).jpg",
  "/separei/separe (105).jpg",
  "/separei/separe (106).jpg",
  "/separei/separe (107).jpg",
  "/separei/separe (108).jpg",
  "/separei/separe (109).jpg",
  "/separei/separe (110).jpg",
  "/separei/separe (111).jpg",
  "/separei/separe (112).jpg",
  "/separei/separe (113).jpg",
  "/separei/separe (114).jpg",
  "/separei/separe (115).jpg",
  "/separei/separe (116).jpg",
  "/separei/separe (117).jpg",
  "/separei/separe (118).jpg",
  "/separei/separe (119).jpg",
  "/separei/separe (120).jpg",
  "/separei/separe (121).jpg",
  "/separei/separe (122).jpg",
  "/separei/separe (123).jpg",
  "/separei/separe (124).jpg",
  "/separei/separe (125).jpg",
  "/separei/separe (126).jpg",
  "/separei/separe (127).jpg",
  "/separei/separe (128).jpg",
  "/separei/separe (129).jpg",
  "/separei/separe (130).jpg",
  "/separei/separe (131).jpg",
  "/separei/separe (132).jpg",
  "/separei/separe (133).jpg",
  "/separei/separe (134).jpg",
  "/separei/separe (135).jpg",
  "/separei/separe (136).jpg",
  "/separei/separe (137).jpg",
  "/separei/separe (138).jpg",
  "/separei/separe (139).jpg",
  "/separei/separe (140).jpg",
  "/separei/separe (141).jpg",
  "/separei/separe (142).jpg",
  "/separei/separe (143).jpg",
  "/separei/separe (144).jpg",
  "/separei/separe (145).jpg",
  "/separei/separe (146).jpg",
];

export const stolice: string[] = [
  "/stolice/stolica.jpg",
  "/stolice/stolica (2).jpg",
  "/stolice/stolica (3).jpg",
  "/stolice/stolica (4).jpg",
  "/stolice/stolica (5).jpg",
  "/stolice/stolica (6).jpg",
  "/stolice/stolica (7).jpg",
  "/stolice/stolica (8).jpg",
  "/stolice/stolica (9).jpg",
  "/stolice/stolica (10).jpg",
  "/stolice/stolica (11).jpg",
  "/stolice/stolica (12).jpg",
  "/stolice/stolica (13).jpg",
  "/stolice/stolica (14).jpg",
  "/stolice/stolica (15).jpg",
  "/stolice/stolica (16).jpg",
  "/stolice/stolica (17).jpg",
  "/stolice/stolica (18).jpg",
  "/stolice/stolica (19).jpg",
  "/stolice/stolica (20).jpg",
  "/stolice/stolica (21).jpg",
  "/stolice/stolica (22).jpg",
  "/stolice/stolica (23).jpg",
  "/stolice/stolica (24).jpg",
  "/stolice/stolica (25).jpg",
  "/stolice/stolica (26).jpg",
  "/stolice/stolica (27).jpg",
  "/stolice/stolica (28).jpg",
  "/stolice/stolica (29).jpg",
  "/stolice/stolica (30).jpg",
  "/stolice/stolica (31).jpg",
];

export const stolovi: string[] = [
  "/stolovi/sto.jpg",
  "/stolovi/sto (2).jpg",
  "/stolovi/sto (3).jpg",
  "/stolovi/sto (4).jpg",
  "/stolovi/sto (5).jpg",
  "/stolovi/sto (6).jpg",
  "/stolovi/sto (7).jpg",
  "/stolovi/sto (8).jpg",
  "/stolovi/sto (9).jpg",
  "/stolovi/sto (10).jpg",
  "/stolovi/sto (11).jpg",
];

export const enterijeri: string[] = [
  "/enterijeri/enterijer.jpg",
  "/enterijeri/enterijer (2).jpg",
  "/enterijeri/enterijer (3).jpg",
  "/enterijeri/enterijer (4).jpg",
  "/enterijeri/enterijer (5).jpg",
  "/enterijeri/enterijer (6).jpg",
  "/enterijeri/enterijer (7).jpg",
  "/enterijeri/enterijer (8).jpg",
  "/enterijeri/enterijer (9).jpg",
  "/enterijeri/enterijer (10).jpg",
  "/enterijeri/enterijer (11).jpg",
  "/enterijeri/enterijer (12).jpg",
  "/enterijeri/enterijer (13).jpg",
  "/enterijeri/enterijer (14).jpg",
  "/enterijeri/enterijer (15).jpg",
  "/enterijeri/enterijer (16).jpg",
  "/enterijeri/enterijer (17).jpg",
  "/enterijeri/enterijer (18).jpg",
  "/enterijeri/enterijer (19).jpg",
  "/enterijeri/enterijer (20).jpg",
  "/enterijeri/enterijer (21).jpg",
  "/enterijeri/enterijer (22).jpg",
  "/enterijeri/enterijer (23).jpg",
  "/enterijeri/enterijer (24).jpg",
  "/enterijeri/enterijer (25).jpg",
  "/enterijeri/enterijer (26).jpg",
  "/enterijeri/enterijer (27).jpg",
  "/enterijeri/enterijer (28).jpg",
  "/enterijeri/enterijer (29).jpg",
  "/enterijeri/enterijer (30).jpg",
  "/enterijeri/enterijer (31).jpg",
  "/enterijeri/enterijer (32).jpg",
  "/enterijeri/enterijer (33).jpg",
  "/enterijeri/enterijer (34).jpg",
  "/enterijeri/enterijer (35).jpg",
  "/enterijeri/enterijer (36).jpg",
  "/enterijeri/enterijer (37).jpg",
  "/enterijeri/enterijer (38).jpg",
  "/enterijeri/enterijer (39).jpg",
  "/enterijeri/enterijer (40).jpg",
  "/enterijeri/enterijer (41).jpg",
  "/enterijeri/enterijer (42).jpg",
  "/enterijeri/enterijer (43).jpg",
  "/enterijeri/enterijer (44).jpg",
  "/enterijeri/enterijer (45).jpg",
  "/enterijeri/enterijer (46).jpg",
  "/enterijeri/enterijer (47).jpg",
  "/enterijeri/enterijer (48).jpg",
  "/enterijeri/enterijer (49).jpg",
  "/enterijeri/enterijer (50).jpg",
  "/enterijeri/enterijer (51).jpg",
  "/enterijeri/enterijer (52).jpg",
  "/enterijeri/enterijer (53).jpg",
  "/enterijeri/enterijer (54).jpg",
  "/enterijeri/enterijer (55).jpg",
  "/enterijeri/enterijer (56).jpg",
];

export const kreveti: string[] = ["/kreveti/krevet.jpg"];
